version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - ./consul/config:/consul/config

  syslog1:
    image: balabit/syslog-ng:latest
    volumes:
      - ./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    depends_on: [consul]

  syslog2:
    image: balabit/syslog-ng:latest
    volumes:
      - ./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    depends_on: [consul]

  loadbalancer:
    build: ./loadbalancer
    depends_on: [consul]
    ports:
      - "514:514/udp"

  logger:
    build: ./logger
    depends_on: [loadbalancer]

